require("options")
require("keymaps")
require("packerPlug")
require("themePlug")
-- require("lualinePlug")
require("nvimTreePlug")
require("treesitterPlug")
require("telescopePlug")
require("formatterPlug")
require("autcmdConfig")
require("indentPlug")
require("autotagPlug")
require("lspPlug")
require("lspsagaPlug")
