require("options")
require("keymaps")
require("packerPlug")
require("treesitterPlug")
require("themePlug")
require("lualinePlug")
require("autotagPlug")
require("lspPlug")
require("lspsagaPlug")
require("telescopePlug")
-- require("nvimTreePlug")
require("formatterPlug")
require("autcmdConfig")
require("indentPlug")
vim.cmd("syntax on")
