-- en before write the buffer i wanna formt
-- vim.api.nvim_create_autocmd("BufWritePre", {
-- 	pattern = { "*.c" },
-- 	callback = function(args)
-- 		print("format")
-- 		vim.lsp.buf.format({ async = true })
-- 	end,
-- })
--
--

-- vim.api.nvim_create_autocmd("BufEnter", {
-- 	pattern = { "*.tsx", "*.ts" },
-- 	callback = function(args)
-- 		vim.cmd("syntax on")
-- 		vim.cmd("TSEnable hightlight")
-- 		print("hello file tsx")
-- 	end,
-- })

--
