vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.cursorline = true
vim.opt.tabstop = 4
vim.opt.smartindent = true
vim.opt.shiftwidth = 2
vim.opt.scrolloff = 8
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.softtabstop = 4
vim.opt.foldmethod = "manual"
vim.opt.completeopt = { "menu", "menuone", "noselect" }
